version: '3'

services:
  django:
    build:
      context: ./django_todo_project  # Indique où se trouve le Dockerfile
    volumes:
      - ./django_todo_project:/app  # Monter le volume pour le code
      - todo_app_react_django_django_data:/app/db
    ports:
      - "8000:8000"  # Mappe le port 8000 de votre machine au port 8000 du container
    environment:
      - DEBUG=True
      - DATABASE_URL=sqlite:///app/db/db.sqlite3

volumes:
  todo_app_react_django_django_data: {}  # Définir le volume
