version: '3'

services:
  django:
    build:
      context: ./django_todo_project  # Indique où se trouve le Dockerfile
    volumes:
      - ./django_todo_project:/app  # Monter le volume pour le code
      - todo_app_react_django_django_data:/app/db.sqlite3  # Monter la base de données SQLite
    ports:
      - "8000:8000"  # Mappe le port 8000 de votre machine au port 8000 du container
    environment:
      - DEBUG=True  # Définir les variables d'environnement pour Django
      - DATABASE_URL=sqlite:///db.sqlite3  # Définir la base de données SQLite pour Django

volumes:
  todo_app_react_django_django_data: {}  # Définir le volume
