version: '3'
services:
  # Service pour Django
  django:
    build:
      context: ./django_todo_project  # Indique où se trouve le Dockerfile
    volumes:
      - ./django_todo_project:/app  # Monter le volume pour le code
    ports:
      - "8000:8000"  # Mappe le port 8000 de votre machine au port 8000 du container
    environment:
      - DEBUG=True  # Définir les variables d'environnement pour Django
      - DATABASE_URL=sqlite:///db.sqlite3  # Définir la base de données SQLite pour Django

  # Service pour React
  react:
    build:
      context: ./react_todo_app  # Indique le dossier du projet React
    volumes:
      - ./react_todo_app:/app  # Monter le volume pour le code React
    ports:
      - "3000:3000"  # Mappe le port 3000 de votre machine au port 3000 du container
    command: "npm start"  # Commande pour démarrer votre application React
