version: '3'

services:
  # Service pour Django
  django:
    build:
      context: ./django_todo_project  # Indique où se trouve le Dockerfile
    volumes:
      - ./django_todo_project:/app  # Monter le volume pour le code
      - ./django_todo_project/db.sqlite3:/app/db.sqlite3  # Monter le fichier SQLite
    ports:
      - "8000:8000"  # Mappe le port 8000 de votre machine au port 8000 du container
    environment:
      - DEBUG=True  # Définir les variables d'environnement pour Django
      - DATABASE_URL=sqlite:///db.sqlite3  # Définir la base de données SQLite pour Django
    command: >
      sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"  # Initialiser DB et démarrer le serveur

volumes:
  django_data:  # Volume Docker pour la base de données SQLite
